### PR TITLE
Added MD File Extension

### PR DESCRIPTION
**Pull request by J-Cake**
Cause you know, Often READMEs take up quite the amount - hey?

### CODE REVIEW

**Comment by Towtow10** [comment]
Markdown is not code.

**Comment by J-Cake** [comment]
what makes it different from HTML?

**Comment by Towtow10** [comment]
I originally saw it as being used for documentation, however it occurs to me that web content is sometimes made from markdown, I will merge the request now.

**Comment by J-Cake** [comment]
@Towtow10 Thank you for accepting this! ☺

**Pull request merged**
